# Generated by Django 2.1.7 on 2022-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190228_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.ImageField(max_length=20, upload_to='song_img/%Y/%m', verbose_name='歌曲图片'),
        ),
    ]
