# Generated by Django 2.1.7 on 2022-12-17 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0006_auto_20220818_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSongRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('num', models.IntegerField(verbose_name='听歌次数')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(max_length=50, upload_to='static/songImg', verbose_name='歌曲文件'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.ImageField(max_length=50, upload_to='static/songFile', verbose_name='歌曲图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.FileField(default='暂无歌词', max_length=50, upload_to='static/songLyric', verbose_name='歌词'),
        ),
        migrations.AddField(
            model_name='usersongrecord',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='歌名'),
        ),
        migrations.AddField(
            model_name='usersongrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
