# Generated by Django 2.1.7 on 2024-03-26 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0007_auto_20221217_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('listen_date', models.DateTimeField(verbose_name='听歌时间')),
            ],
            options={
                'verbose_name': '用户听歌记录',
                'verbose_name_plural': '用户听歌记录',
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(max_length=50, upload_to='static/songFile', verbose_name='歌曲文件'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.ImageField(max_length=50, upload_to='static/songImg', verbose_name='歌曲图片'),
        ),
        migrations.AddField(
            model_name='listenrecord',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='听歌歌曲'),
        ),
        migrations.AddField(
            model_name='listenrecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='听歌用户'),
        ),
    ]
