# Generated by Django 2.1.7 on 2024-03-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20240327_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenrecord',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='listenrecord',
            old_name='user_id',
            new_name='user',
        ),
    ]
